name: ci-node
on: 
  pull-request:
    branches:
      - develop
jobs:
  check-app:
    strategy:
      matrix:
        version: ['20', '21', '22']
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Instala Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Instalar dependências
        run: npm ci
      - name: Rodar testes
        run: node --test